### PR TITLE
error on latest versions of request

### PR DESCRIPTION
**Pull request by pgte**
On latest versions of request, when you get a JSON response, request already passes you a parsed object as the body.
Now, only if the given body is a string we try to parse it.

### CODE REVIEW

**Comment by pgte** [comment]
@jhs yup, that's fixed for me, thanks!

**Comment by jhs** [comment]
Great!

However I will miss /some_regex/.test(). It is the only string match that looks at all nice in Javascript. I really want:

```
if(doc._id =~ /^A-Z/)
    do_stuff(); // :(
```

**Comment by pgte** [comment]
@jhs, just to clarify, this issue is related to the request version, is fixed,
The other issue I found, (#4) is related with the couchdb js interpreter versions and regexp.test / exec, which is still occurs to  me:
https://github.com/iriscouch/cqs/issues/3 :)

**Comment by jhs** [comment]
@pgte You are right. No more GitHub before coffee.

**Pull request closed without merging**
